### PR TITLE
1.7.10 Witchery-Vamp Dupe Glitch Fix

### PR DESCRIPTION
**Pull request by xaleb**
Hello, this is xaleb from Minecraft forums. This is severely late...However, I already had it done and wanted to submit it. This is my fix for your 1.7.10 version of lootable bodies I asked you for permission to do three months ago. It makes the mod more compatible with adventure backpacks, and witchery vampires while removing duplication errors. As well as makes it much more reliable as a whole in terms of conflict solving. I took the liberty of bumping it up to 1.3.8 as well. I also noticed that occasionally the bodies don't let you open them up right away immediately after death. This applies to both your code, and my edits. I may attempt to solve the problem. Please check the code, and possibly accept the request. I have included the finished .jar file as well.

Thank you! 
EDITED 8/9/16:
[LootableBodies-pull request.zip](https://github.com/cyanobacterium/DrCyanos_Lootable-Bodies/files/410132/LootableBodies-pull.request.zip)

### CODE REVIEW

**Comment by jriwanek** [comment]
I'd suggest you resubmit without all the formatting changes.

**Comment by xaleb** [comment]
Yeah, I'm a scrub at github, I've never used it til now. The formatting changes were me trying to fix it not opening correctly immediately after dying. And was heavily oriented with me messing around with a single document. The rest of the formatting is actually me removing and adding lines. I can clean this up. However, I have no idea what the fudge I'm doing on this site. Do I just edit my fork by upload and resend pull request?

**Comment by jriwanek** [comment]
Should be a case of just edit your stuff on that branch, shouldn't need to resend the pull request.

**Comment by xaleb** [comment]
Thanks for waiting! I have fixed the formatting changes, and simplified the code a bit. I have also edited the zip file above in the first post. Please review!

**Comment by jriwanek** [comment]
Thanks, now we just need to Wait for Cyano to show up and merge it.

**Pull request merged**
