### PR TITLE
Fixing warnings & 1.10.2

### PR DESCRIPTION
**Pull request by HoldYourWaffle**
Wanted to update this mod to 1.10.2 cause I need it, but it doesn't require any updating. So I just fixed some warnings :) (or surpressed them)

So the actual purpose of this PR is to let you know that you can add an 1.10.2 build...

### CODE REVIEW

**Comment by HoldYourWaffle** [comment]
Wait it doesn't gradle-build for some reason...
Fixing it right now

**Comment by HoldYourWaffle** [comment]
Okay so it doesn't work with java 7 or earlier.
Many people still use java 7 and if i'm not mistaken is the default mc-runtime java 6.
I can fix the source so it's compatible with java 6 or I can change the gradle to build at java 8.
What's the best in your opinion?

**Comment by CruzBishop** [comment]
Forge now recommends updating to Java 8 when running a client using Java 7, so there's at least a possibility of being restricted to 8 in the future.

I don't have the exact warning screen up right now, so I'm not sure if there's a notice saying that some mods may require it

**Comment by jriwanek** [comment]
Many of Cyano's mods require Java 8, as @CruzBishop says, forge now nags for java 8, Mojang's official launcher uses java 8, Java 6 is End of life, So, go with Java 8.

**Comment by jriwanek** [comment]
Also, what was the purpose of downgrading gradle from 2.13 to 2.7?

**Comment by CruzBishop** [comment]
@jriwanek Could it have been introduced by Supreme Leader Eclipse? I'm pretty sure it's what @HoldYourWaffle uses :smile: 

<sup><sup><sup>IntelliJ IDEA for life :D</sup></sup></sup>

**Comment by HoldYourWaffle** [comment]
@CruzBishop i guess...
I'll try to revert that.

**Comment by HoldYourWaffle** [comment]
Should be fixed

**Comment by jriwanek** [comment]
@CruzBishop I've never had Eclipse mess with my gradle Wrapper before.

@HoldYourWaffle mappings = "snapshot_20160518"

http://export.mcpbot.bspk.rs/snapshot/

Earliest 1.10.2 mapping is 20160627

I assume you're actually testing these changes?

**Comment by HoldYourWaffle** [comment]
@jriwanek I did and it's working for me... (I'm sorry if I'm misunderstanding anything, I haven't slept well for 4 weeks now so I'm kind of a zombie)

**Comment by jriwanek** [comment]
Hmm..., the 1.10.2 mdk refs the same version, Nonetheless, I suggest updating to the latest.

Unfortunately, I can only review for you as I don't have commit access to this repo, but I'll do a build test later on this week.

**Comment by HoldYourWaffle** [comment]
+1

**Comment by jriwanek** [comment]
@HoldYourWaffle Cyano did an update to 1.10.2 already, if you'd like to clean up your changeset, I'll see about merging it.

**Comment by HoldYourWaffle** [comment]
I'm on it once I got weekend.

**Comment by jriwanek** [comment]
Future Development taking place at:
https://github.com/MinecraftModDevelopment/LootableBodies/
btw.

**Pull request closed without merging**
